axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.4
enable_trigger: 2  # Left trigger (LT) button

axis_linear_turbo: 4  # Right thumb stick vertical
scale_linear_turbo: 1.5
axis_angular_turbo: 3  # Right thumb stick horizontal
scale_angular_turbo: 1.0
enable_turbo_trigger: 5  # Right trigger (RT) button

button_map:
  A: 0
  B: 1
  X: 2
  Y: 3
  L: 4
  R: 5
