robot_names:
  - X1
  - X2
  - Iris
  - Neo11

button_robot_map:
  A: X1
  B: X2
  X: Iris
  Y: Neo11

flashlight_service_suffixes:
  # X1 and X2
  - /right_headlight/enable
  - /center_right_headlight/enable
  - /center_left_headlight/enable
  - /left_headlight/enable
  # Iris and Pelican
  - /downward_flashlight/enable
  - /left_flashlight/enable
  - /right_flashlight/enable

robot_address_map:
  X1: X1
  X2: X2
  Iris: Iris
  Neo11: Neo11

select_led_service_suffixes:
  # X1
  - /left_lateral_front_led/enable
  - /left_lateral_rear_led/enable
  - /rear_left_led/enable
  - /right_lateral_front_led/enable
  - /right_lateral_rear_led/enable
  - /rear_right_led/enable
  # X2
  - /left_lateral_led/enable
  - /right_lateral_led/enable
  # Iris and Pelican
  - /left_led/enable
  - /right_led/enable

comm_led_service_suffixes:
  # X1 and X2
  - /rear_center_led/enable
  # Iris and Pelican
  - /center_led/enable
